- name: playbook - 3
  hosts: all
  tasks:
    - name: print the host details_1
      debug:
        msg: "Domain name of ansible: {{ansible_lo.features.rx_udp_gro_forwarding}}"

    - name: print the host details_2
      debug:
        msg: "Domain name of ansible: {{ansible_product_version}}"        

    - name: print the host details_3
      debug:
        msg: "Domain name of ansible: {{ansible_distribution}}"              