- name: playbook - 3
  hosts: all
  tasks:
    - name: print the host details_1
      debug:
        msg: "Domain name of ansible: {{ansible_lo.features.rx_udp_gro_forwarding}}"
      tags: 1

    - name: print the host details_2
      debug:
        msg: "product_version name of ansible: {{ansible_product_version}}"
      tags: 2

    - name: print the host details_3
      debug:
        msg: "Distribution name of ansible: {{ansible_distribution}}"  
      tags: 3            