- name: playbook-4
  hosts: all
  tasks:
    - name: escalation for users
      shell: id
      register: out

    - name: escalation print
      debug:
        msg: "print escalation of server: {{out}}"   

    - name: install services
      apt-get:
        name: tree
        state: latest
