- name: Playbook1
  hosts: all
  vars: url.yml
  tasks:

  - name: Print messages_1
    debug:
      msg: "{{URL}}"

  - name: Print messages_2
    debug:
      msg: "{{URL}}"    
    vars:
      URL: cloudblitz.in/aws